# Generated by Django 4.1.6 on 2023-02-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simontest', '0002_alter_bookinfo_options_bookinfo_commentcount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleinfo',
            options={'verbose_name': '人物管理'},
        ),
        migrations.AlterModelTable(
            name='peopleinfo',
            table='Peopleinfo',
        ),
    ]
